/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'orator-navy': 'var(--color-orator-navy)',
        'orator-gold': 'var(--color-orator-gold)',
        'orator-crimson': 'var(--color-orator-crimson)',
        'orator-cream': 'var(--color-orator-cream)',
        'orator-slate-white': 'var(--color-orator-slate-white)',
        'orator-charcoal': 'var(--color-orator-charcoal)',
        'tertiary-fixed-dim': '#cac6be',
        'inverse-on-surface': '#2b303d',
        'tertiary-fixed': '#e7e2da',
        'on-tertiary-container': '#4a4842',
        'primary-container': 'var(--color-orator-gold)',
        'on-primary-container': 'var(--color-orator-navy)',
        'error-container': 'var(--color-orator-crimson)',
        'on-tertiary-fixed-variant': '#494741',
        'error': 'var(--color-orator-crimson)',
        'on-secondary-container': 'var(--color-orator-slate-white)',
        'primary': 'var(--color-orator-gold)',
        'secondary-container': 'var(--color-orator-navy)',
        'on-secondary': 'var(--color-orator-cream)',
        'on-secondary-fixed-variant': 'var(--color-orator-crimson)',
        'primary-fixed': 'var(--color-orator-gold)',
        'tertiary': 'var(--color-orator-slate-white)',
        'inverse-primary': 'var(--color-orator-charcoal)',
        'surface-container-lowest': 'var(--color-orator-navy)',
        'on-error': 'var(--color-orator-cream)',
        'tertiary-container': 'var(--color-orator-charcoal)',
        'on-tertiary': 'var(--color-orator-cream)',
        'background': 'var(--color-orator-navy)',
        'surface-dim': 'var(--color-orator-navy)',
        'surface-container': 'var(--color-orator-charcoal)',
        'outline-variant': 'var(--color-orator-charcoal)',
        'surface-container-highest': 'var(--color-orator-charcoal)',
        'outline': 'var(--color-orator-slate-white)',
        'on-secondary-fixed': 'var(--color-orator-navy)',
        'on-background': 'var(--color-orator-slate-white)',
        'surface': 'var(--color-orator-charcoal)',
        'secondary': 'var(--color-orator-crimson)',
        'on-tertiary-fixed': 'var(--color-orator-navy)',
        'inverse-surface': 'var(--color-orator-cream)',
        'on-surface-variant': 'var(--color-orator-slate-white)',
        'on-primary-fixed': 'var(--color-orator-navy)',
        'on-surface': 'var(--color-orator-cream)',
        'secondary-fixed-dim': 'var(--color-orator-crimson)',
        'surface-tint': 'var(--color-orator-gold)',
        'primary-fixed-dim': 'var(--color-orator-gold)',
        'on-error-container': 'var(--color-orator-cream)',
        'surface-bright': 'var(--color-orator-charcoal)',
        'on-primary': 'var(--color-orator-navy)',
        'surface-variant': 'var(--color-orator-charcoal)',
        'surface-container-high': 'var(--color-orator-charcoal)',
        'on-primary-fixed-variant': 'var(--color-orator-gold)',
        'secondary-fixed': 'var(--color-orator-crimson)',
        'surface-container-low': 'var(--color-orator-navy)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        'stack-md': '3rem',
        'safe-margin': 'clamp(1.5rem, 7vw, 10rem)',
        'stack-lg': '6rem',
        'gutter': '2rem',
        'stack-xl': '10rem',
      },
      fontFamily: {
        'headline-lg-mobile': ['Syne'],
        'display-xl': ['Syne'],
        'body-lg': ['Hanken Grotesk'],
        'label-caps': ['JetBrains Mono'],
        'headline-lg': ['Syne'],
        'body-md': ['Hanken Grotesk'],
        'quote-serif': ['Cormorant Garamond'],
        'display-xl-mobile': ['Syne'],
      },
      fontSize: {
        'headline-lg-mobile': ['32px', { lineHeight: '38px', fontWeight: '700' }],
        'display-xl': ['120px', { lineHeight: '108px', letterSpacing: '-0.05em', fontWeight: '800' }],
        'body-lg': ['20px', { lineHeight: '34px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.12em', fontWeight: '500' }],
        'headline-lg': ['48px', { lineHeight: '54px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '28px', fontWeight: '400' }],
        'quote-serif': ['28px', { lineHeight: '38px', fontWeight: '500' }],
        'display-xl-mobile': ['clamp(2.5rem, 10vw, 4rem)', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
}
